# Gradient Descent

In [1]:
import torch 
import torch.nn.functional as F 

In [2]:
target = torch.FloatTensor([[.1, .2, .3],
                             [.4, .5, .6],
                             [.7, .8, .9]])

In [3]:
x = torch.rand_like(target)
# This means the final scalar will be differentiated by x 
x.requires_grad = True
# Can get gradient of x, after differentiation

x

tensor([[0.0058, 0.3308, 0.9491],
        [0.6792, 0.1535, 0.4861],
        [0.0156, 0.5448, 0.4289]], requires_grad=True)

In [4]:
loss = F.mse_loss(x, target)
loss

tensor(0.1571, grad_fn=<MseLossBackward>)

In [5]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold : 
    iter_cnt += 1 
    
    loss.backward()  # calculate descent 
    
    x = x - learning_rate * x.grad
    
    # Don't need to be aware of this now 
    x.detach_()
    x.requires_grad_(True)
    
    loss = F.mse_loss(x, target)
    
    print('%d-th Loss : %.4e' % (iter_cnt, loss))
    print(x)
    

1-th Loss : 9.5029e-02
tensor([[0.0268, 0.3017, 0.8049],
        [0.6172, 0.2305, 0.5114],
        [0.1677, 0.6015, 0.5336]], requires_grad=True)
2-th Loss : 5.7487e-02
tensor([[0.0430, 0.2791, 0.6927],
        [0.5689, 0.2904, 0.5311],
        [0.2860, 0.6456, 0.6150]], requires_grad=True)
3-th Loss : 3.4776e-02
tensor([[0.0557, 0.2615, 0.6054],
        [0.5314, 0.3370, 0.5464],
        [0.3780, 0.6799, 0.6783]], requires_grad=True)
4-th Loss : 2.1037e-02
tensor([[0.0655, 0.2479, 0.5376],
        [0.5022, 0.3732, 0.5583],
        [0.4495, 0.7066, 0.7276]], requires_grad=True)
5-th Loss : 1.2726e-02
tensor([[0.0732, 0.2372, 0.4848],
        [0.4795, 0.4014, 0.5676],
        [0.5052, 0.7274, 0.7659]], requires_grad=True)
6-th Loss : 7.6986e-03
tensor([[0.0792, 0.2290, 0.4437],
        [0.4618, 0.4233, 0.5748],
        [0.5485, 0.7435, 0.7957]], requires_grad=True)
7-th Loss : 4.6572e-03
tensor([[0.0838, 0.2225, 0.4118],
        [0.4481, 0.4403, 0.5804],
        [0.5822, 0.7561, 0.8189]]