In [1]:
import torch

## Raw Linear Layer
<center>
$y = x\cdot W+b$  
<center>
where $x \in \mathbb{R}^{N \times n},y \in \mathbb{R}^{N \times m}$  
  
<center>
Thus, $W \in \mathbb{R}^{n \times n}$ and $b \in \mathbb{m}$    

In [3]:
W = torch.FloatTensor([[1,2],
                       [3,4],
                       [5,6]])
b = torch.FloatTensor([2,2])

In [4]:
print(W.size())
print(b.size())

torch.Size([3, 2])
torch.Size([2])


In [5]:
def linear(x, W, b) : 
    y = torch.matmul(x, W) + b
    
    return y 

In [6]:
x = torch.FloatTensor([[1,1,1],
                       [2,2,2],
                       [3,3,3],
                       [4,4,4]])

print(x.size())

torch.Size([4, 3])


In [7]:
y = linear(x, W, b)

In [8]:
print(y.size())

torch.Size([4, 2])


## nn.Module

In [9]:
import torch.nn as nn 

In [10]:
# not good example 
class MyLinear(nn.Module) :
    def __init__(self, input_dim=3, output_dim=2) :
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        
        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)
        
    def forward(self, x) : 
        y = torch.matmul(x, self.W) + self.b
        
        return y

In [11]:
linear = MyLinear(3, 2)
y = linear(x)

In [12]:
print(y.size())

torch.Size([4, 2])


In [13]:
for p in linear.parameters() : 
    print(p)

In [14]:
# good example
class MyLinear(nn.Module) :
    def __init__(self, input_dim=3, output_dim=2) :
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        
        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))
        
    def forward(self, x) : 
        y = torch.matmul(x, self.W) + self.b
        
        return y

In [15]:
linear = MyLinear(3, 2)
y = linear(x)

In [16]:
print(y.size())

torch.Size([4, 2])


In [17]:
for p in linear.parameters() : 
    print(p)

Parameter containing:
tensor([[1.0549e-08, 4.1955e-08],
        [4.2295e-05, 1.7280e-04],
        [5.4645e-05, 2.7199e+23]], requires_grad=True)
Parameter containing:
tensor([3.0156, 2.0000], requires_grad=True)


## nn.Linear

In [19]:
linear = nn.Linear(3, 2)
y = linear(x)

In [20]:
print(y.size())

torch.Size([4, 2])


In [21]:
for p in linear.parameters() : 
    print(p)

Parameter containing:
tensor([[ 0.0687, -0.3646, -0.5754],
        [ 0.4196,  0.4037, -0.1210]], requires_grad=True)
Parameter containing:
tensor([-0.2392,  0.1269], requires_grad=True)


### nn.Module can contain other nn.Module's child classes.

In [27]:
class MyLinear(nn.Module) : 
    def __init__(self, input_dim = 3, output_dim = 2) : 
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        
        self.linear = nn.Linear(input_dim, output_dim)
    
    def forward(self, x) : 
        y = self.linear(x)
        
        return y

In [28]:
linear = MyLinear(3, 2)
y = linear(x)

In [29]:
print(y.size())

torch.Size([4, 2])


In [30]:
for p in linear.parameters() : 
    print(p)

Parameter containing:
tensor([[-0.5232, -0.2268, -0.4730],
        [-0.5492, -0.4650,  0.3427]], requires_grad=True)
Parameter containing:
tensor([-0.5218, -0.4498], requires_grad=True)
