# PyTorch Tensor Operations

In [2]:
import torch

## Inplace Operations

In [ ]:
printz

## Arithmetic Element-wise Operations

In [5]:
a = torch.FloatTensor([[1, 2],
                       [3, 4]])
b = torch.FloatTensor([[2, 2,],
                       [3, 3]])

## Inplace Operations

In [6]:
print(a)
print(a.mul(b)) # 결과 반환
print(a) # a는 변화가 없음
print(a.mul_(b)) # a에 결과를 입력
print(a) # a의 값이 새로 부여되었음

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


## Sum. Mean(Dimension Reducing Operations)

In [7]:
x = torch.FloatTensor([[1,2], 
                       [3,4]])

In [8]:
print(x.sum())
print(x.mean())

tensor(10.)
tensor(2.5000)


In [10]:
# 특정 dimension에 대해서만 연산 수행
print(x.sum(dim = 0))
print(x.sum(dim = -1))

tensor([4., 6.])
tensor([3., 7.])


## Broadcast in Operations

In [13]:
x = torch.FloatTensor([[1,2]])
y = torch.FloatTensor([[4,8]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([1, 2])


In [14]:
z = x + y
print(z)
print(z.size())

tensor([[ 5., 10.]])
torch.Size([1, 2])


## Tensor + scalar

In [16]:
x = torch.FloatTensor([[1, 2], 
                       [3, 4]])
y = 1 

print(x.size())

torch.Size([2, 2])


In [17]:
z = x + y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


## Tensor + Vector

In [18]:
x = torch.FloatTensor([[1, 2],
                       [4, 8]])
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

torch.Size([2, 2])
torch.Size([2])


In [19]:
z = x + y 
print(z)
print(z.size())

tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


In [20]:
x = torch.FloatTensor([[[1,2]]])
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

torch.Size([1, 1, 2])
torch.Size([2])


In [21]:
z = x + y 
print(z)
print(z.size())

tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


## Tensor + Tensor 

In [22]:
x = torch.FloatTensor([[1,2]])
y = torch.FloatTensor([[3],
                       [5]])
print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2, 1])


In [23]:
z = x + y 
print(z)
print(z.size())

tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


## Failure case 

In [24]:
x = torch.FloatTensor([[[1,2],
                        [4,8]]])
y = torch.FloatTensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
print(x.size())
print(y.size())

torch.Size([1, 2, 2])
torch.Size([3, 3])


In [25]:
z = x + y

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2