# PyTorch Tensor Manipulations

In [1]:
import torch

## Tensor Shaping

### reshape : Change Tensor Shape

In [2]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                       [[5,6],
                        [7,8]],
                       [[9,10],
                        [11,12]]])

print(x.size())                     

torch.Size([3, 2, 2])


In [3]:
print(x.reshape(12)) # 12 = 3 * 2 * 2 
print(x.reshape(-1)) 

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [4]:
print(x.reshape(3, 4))
print(x.reshape(3, -1))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [5]:
print(x.reshape(3, 1, 4))
print(x.reshape(-1, 1, 4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [6]:
print(x.reshape(3,2,2,1))

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


## squeeze : Remove dimension which has only one element.

In [7]:
x = torch.FloatTensor([[[1,2],
                        [3,4]]])
print(x.size())

torch.Size([1, 2, 2])


Remove any dimension which has only one element.

- len이 1인 dimension을 제거

- 1x2x2 -> 2x2

In [8]:
print(x.squeeze())
print(x.squeeze().size())

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


In [9]:
print(x.squeeze().size())
print(x.squeeze(1).size())

torch.Size([2, 2])
torch.Size([1, 2, 2])


## unsqueeze : Insert dimension at certain index. 

In [10]:
x = torch.FloatTensor([[1,2],
                       [3,4]])
print(x.size())

torch.Size([2, 2])


In [11]:
print(x.unsqueeze(2))
print(x.unsqueeze(-1))
print(x.reshape(2, 2, -1))

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
