# PyTorch Tensor

In [1]:
import torch

## Tensor Allocation

In [3]:
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [4]:
# int 를 담는 long tensor
# index와 같은 값들을 담을 때 주로 사용
lt = torch.LongTensor([[1, 2],
                       [3, 4]])
lt

tensor([[1, 2],
        [3, 4]])

In [5]:
# 0 또는 1등의 값을 담은 byte tensor
bt = torch.ByteTensor([[1, 0], 
                       [0, 1]])
bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [6]:
# random하게 생성(garbage값)
x = torch.FloatTensor(3, 2)
x

tensor([[3.3209e-09, 2.0683e+20],
        [2.6193e+20, 8.3575e+20],
        [2.1457e-07, 5.2304e+22]])

## NumPy Compatibility 
PyTorch의 장점 중 하나는 numpy와 호환이 잘 된다는 것

In [7]:
import numpy as np 

# Define numpy array 
x = np.array([[1, 2],
              [3, 4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [8]:
# numpy로부터 가져오기
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>


In [9]:
# tensor를 numpy로 보내기
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


## Tensor Type-casting

In [14]:
# ft -> lt
ft.long()

tensor([[1, 2],
        [3, 4]])

In [15]:
# lt -> ft
lt.float()

tensor([[1., 2.],
        [3., 4.]])

In [16]:
torch.FloatTensor([1, 0]).byte()

tensor([1, 0], dtype=torch.uint8)

## Get Shape

In [17]:
x = torch.FloatTensor([[[1, 2],
                       [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

Get tensor shape

In [19]:
print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


Get the number of dimensions in the tensor

In [37]:
print(x.dim())
print(len(x.size())) # size는 각 축의 dim을 알려주는 값들로 구성된 벡터 -> len -> dim 

3
3


Get the number of elements in the last dimension.

In [41]:
print(x.size(-1))
print(x.shape[-1])

2
2
